def menu():
    print("\n" + "*" * 45)
    print("Menu de gestion de stock")
    print("*" * 45 + "\n")
    print("\t1. Agregar producto")
    print("\t2. Modificar cantidad de stock")
    print("\t3. Eliminar producto")
    print("\t4. Mostrar productos")
    print("\t5. Mostrar productos con bajo stock")
    print("\t6. Salir")
    print("\n" + "*" * 45)